[package]
authors = ["chevdor <chevdor@gmail.com>", "Wilfried Kopp <wilfried@parity.io"]
description = "subwasm is a utility that works on WASM Runtime of Substrate based chains"
edition = "2018"
homepage = "https://gitlab.com/chevdor/subwasm"
keywords = ["wasm", "cli", "substrate", "blockchain", "runtime", "polkadot", "kusama"]
license = "MIT"
name = "subwasm"
readme = "README.md"
repository = "https://gitlab.com/chevdor/subwasm"
version = "0.10.0"

[dependencies]
assert_cmd = "1.0.4"
clap = "3.0.0-beta.2"
color-eyre = "0.5.11"
env_logger = "0.8.3"
log = "0.4.14"
substrate-runtime-proposal-hash = {path = "../libs/substrate-runtime-proposal-hash", optional = true}
subwasmlib = {path = "../lib"}
wasm-loader = {path = "../libs/wasm-loader"}
wasm-testbed = {path = "../libs/wasm-testbed"}
